[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "4e1f8c0e9c34dd36443cd6b6ec034c73efe8b71e"
os = "macos"

    [[aws_c_sdkutils.download]]
    sha256 = "d9f4438db507fb5d0b2ae5c2e211e68eec444fd1db528f7a8e71441936119c32"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.aarch64-apple-darwin.tar.gz"
[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "b7eac1d03350c5e4d4a0d834adb72224ea466520"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "b1e1496b56223f58068def5c373a8c05342d3412b81dc0b4d9429693c672778b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.aarch64-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "23ef1198f8863d3a4c6b09f62501a32ecbd00d6f"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "b604650ae91d5318c67416a08eaf1ac2652b2cd7c0c61843f1969578176e38b5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.aarch64-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a50f5346b7766db3a348aa1b1e573096f362a755"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "f275c436a01c86aa53a5b25f6c62a1c24e60f9a6ef985aa51fcbf9521b953912"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b6486c530c34330cc9733fbf07f1e080c0dbf76d"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "722dff9d3b97dd867a90c52f7c444fd51095896b0469aa7b8e158e207486a0ce"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.armv6l-linux-musleabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94c538131cf358398cf76bfd9aedf33e4a32d934"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "3ab87eb19f07711c0a107157e81b5345fb33d2747a470596532e87d25c258819"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3b37cd2ed95250b64c27d6125313fc9011ee4866"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "dfa5c4aab82ff9009ad35da1b160ef0f7ee80bac243fe4d712f7568e9ec74b19"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.armv7l-linux-musleabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "i686"
git-tree-sha1 = "20e23863f9f6fc603e567aa4c901e8e3f99936dd"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "40b1c7f254c04134ee1c23aebe6b3b14784b793c7b4811f4ebe54f88a0b96e05"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.i686-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "i686"
git-tree-sha1 = "71e1994999650261bb8df7c2abeae2b99d8ab073"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "5bf430a23942ea32b3dbd8c439323297bba03e2e348500ff65c91a4f9f2d0d16"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.i686-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "powerpc64le"
git-tree-sha1 = "5c4e7a543eef142b774b5a71d2084c25141950c3"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "961c44f083932c91fab9d01482b4b0380c3ff43b0451690820694e462b6efce6"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.powerpc64le-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "bef2dd35b852187350f72b21552d2836c68f8d39"
os = "macos"

    [[aws_c_sdkutils.download]]
    sha256 = "9a09f14483b944c73b79b8549faec92fa36713e5949530026bca53e7d3374ee0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.x86_64-apple-darwin.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "276d3d6d86bc40279e2668ce48e1e27943638c16"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "4ef8f2484cec5103332087a8b58d03135f56f634f5081a626da6c60c3b222d42"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.x86_64-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "b81be0435cc9b4c44733b6d1c78b3b1256c4010d"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "ac36e7c3b8508a72d4547c0a5dfd4a61397cdf5dba7ffc3aeeccc869d5a53997"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.x86_64-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "a0703dbffa434acae075d775b86d0bcb87825efa"
os = "freebsd"

    [[aws_c_sdkutils.download]]
    sha256 = "ff706e379405e0de2070aa3430449dca643ac806820cd5b8b18efc9d49cbcab1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.x86_64-unknown-freebsd.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "e65498df51076eb67014a43671691d1359583332"
os = "windows"

    [[aws_c_sdkutils.download]]
    sha256 = "255fc619758ce4a83503d608cefa9108dfe6795061640775d77669560e0c5753"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.18+0/aws_c_sdkutils.v0.1.18.x86_64-w64-mingw32.tar.gz"
