[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "0d58feceeee60e468e6e06892485f0cdce9abb1c"
os = "macos"

    [[aws_c_sdkutils.download]]
    sha256 = "94043834deeebe39dbc4c168360a040bc56239d87f3c793e68efeb9b64c2bb6b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.aarch64-apple-darwin.tar.gz"
[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "d4c3270a4bdf971a398b3c02e08d585f68f19bd5"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "90a2ba22662be62f7f6362e4cadd86d6172ef69910934cb655367b5271711033"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.aarch64-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "2f6e8bc5e7c92771f2c6b3eedc2aee849d5d5d1e"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "18baa17af625aefc3394755558dd2a4e448b56e16d11f9078a38afc40a1cf90e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.aarch64-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fc6ce975e0d093188cf0f9ee2bd14af7a2260055"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "9a19bfb159dcf10854d68a0aa7893bec09204105f3c30b3d1917b9541ad7e7a9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2fed5a0f3ea095893b267d4c253d0dfb4f97fbbc"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "f47e1b4c5e42e9d9eaf2eed4f9a83973ec496e8782a82e55efc0f19be6fbf35b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.armv6l-linux-musleabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "75a891d5dd563755e72ac39de377aa6c2ccec33b"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "d97c1579ac97b16a8d382c2fe5eca2e3b0b879331774778ca7ae5c019f9c88e4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f17f6e41aa14d9c9bfda0e76b8857be57ef4141c"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "19c2b9d0e01efb4f4080265a358ffe3f2e5a647d3a7330ee8bbafd2dee8b1ba4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.armv7l-linux-musleabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "i686"
git-tree-sha1 = "4150f1b7fdfe037c7cb6a60b5e57bc8f3b02c6c8"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "b6d07ca6961d776c3177cd18bca92b7fdc0a7d0f5d35e5ad500cb60905676407"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.i686-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "i686"
git-tree-sha1 = "f285d10457b316df9b050b5c1f70e111a5f2fb08"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "254b07936315be487b100ee135e53ab5b56e931c9a1e1e44abeb4f67a04b3e1e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.i686-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "powerpc64le"
git-tree-sha1 = "d3d6fdc70052987fa75f87be9acbb6df666fc36b"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "73284d6b778d870024d6208683aa714dd800ffe2a18b003d9e09bf542efd7070"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.powerpc64le-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "b1f4086c479bd714a2cb761d00f0184ac667b090"
os = "macos"

    [[aws_c_sdkutils.download]]
    sha256 = "34b1d016063d68b3b545a8b29c4cc770be260541941415e92a492dabbd74de21"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.x86_64-apple-darwin.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "5a57202320eb1fdbddcea683fa13d8b5d3a9069b"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "846f8787ef547edc3a70e3bc41d50afae0e1b9ac0e43c03e01f01276ddca5d13"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.x86_64-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "18e8c24d5e870886251a22b7c45c31b398e59969"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "460b5315372ae66364fcedef5dc2e67bc05e20bdf4835b8e7e521ba34e93a210"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.x86_64-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "4844674c0784cec1397f8051bdeee00b566b063c"
os = "freebsd"

    [[aws_c_sdkutils.download]]
    sha256 = "d9a6640051b9564135f7fe4b868b77d268fdd6742ac1b36663a3891078cf5689"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.x86_64-unknown-freebsd.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "716ecaa52f17ff4299d60740675a1bba22748592"
os = "windows"

    [[aws_c_sdkutils.download]]
    sha256 = "88be99586e4c5f6b6cfe6551e3c668419ac2641c2b33bcbca04c6cc38414dda2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.16+0/aws_c_sdkutils.v0.1.16.x86_64-w64-mingw32.tar.gz"
