[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "2128a24477edf71f95227859e173717a1cbad226"
os = "macos"

    [[aws_c_sdkutils.download]]
    sha256 = "969557a3bd5666795684f347edaa7c47e3c82081db1561183ff07a169cbb0e78"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.aarch64-apple-darwin.tar.gz"
[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "bc2f970cd9cffacf4e2ebaaa90b167c4af51f53d"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "e89dfb8d6f02eea2fde8e5623549ec353ec561214ff92bb06f6c31a1b97be178"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.aarch64-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "f7e6a82f68fc74d56fb1ac36ea26178826ee205b"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "e5bac15d88b8d7073f0aa9268dc422fa40258346f0dbb281339ad69c9dbb6ce3"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.aarch64-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "076b53c55346437a502b9f0aec22b1f8d0894929"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "47b642349545fc9182f64a557d97b58e48b622f2f08d9a7a973bf6b502a936a1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c6ecf538aaabc9f1ab43dfd069dbc16e26b7ef82"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "afbf3b009fd942e05cb29a5df3be37ea77e024a4ebe8fd2c0772a4a754df755c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.armv6l-linux-musleabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9deeb6f0d026339fd3116333cc6ac2bafa71147f"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "8ec6588c8d23865d3c34c9531f93843fa52d503b50917948eb5a0a79125afe6e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d46f87b149a1b010badd4fef1dfec0d366822f5d"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "53a3bb1cb3b4244a17926533cdab93062a7fd7426346838e5e4d1128c4bf0923"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.armv7l-linux-musleabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "i686"
git-tree-sha1 = "724a2968dd9612e24ee4b71d8c054b72ffa2395f"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "fa07d61211c62c768f0caad71ab224adc9917b3d5209e2f8b8f0a901e3063655"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.i686-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "i686"
git-tree-sha1 = "4aea419f4149d059a0d6dc78a618aadb31e60256"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "9540532aa4dc659e2ee6e319b731ca1a7a59d649aefdd3dfa3468b98ed857464"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.i686-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "powerpc64le"
git-tree-sha1 = "0fb66660c854a004280e640131ff8ecc5de56cee"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "de5337a28337632b4fdd490b9a8622e8d98dda1de9534632107e78b802790eec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.powerpc64le-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "bd8e64089ff116d87b221b860afdf6c9ab37b058"
os = "macos"

    [[aws_c_sdkutils.download]]
    sha256 = "a5dca8e9f548daea9ec2d590edb61f47609431394171ac114704459cc2d66dce"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.x86_64-apple-darwin.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "59656841bb7ad35f89fa2f2fb54611b41ca2faff"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "86ee958bf2734ac9b3d17fc2b8c6790ba75abd2bace7f8df4e470839a44301ed"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.x86_64-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "b0bb30f70d001f3049e81a7d6541675ad4d0a9c7"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "378c3700a13766d8c0b9d9d55016cdb1f13b14a559799bfc0f3eb50aeff65ca9"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.x86_64-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "41e406df21412141f76c30ca9848acaf6108e17a"
os = "freebsd"

    [[aws_c_sdkutils.download]]
    sha256 = "7274a9a4ac9e9895024aeeb670df9f23b7b6c3fbfdd028695efc758e1d427882"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.x86_64-unknown-freebsd.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "c1e50790f6e0296c3adc89122fc7356d8d3952a8"
os = "windows"

    [[aws_c_sdkutils.download]]
    sha256 = "2a701bb72d6d70cf82f95d27aca22ca5c9ad4a7431e6d2f8b2ba3f1cdc9a3c55"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.12+1/aws_c_sdkutils.v0.1.12.x86_64-w64-mingw32.tar.gz"
