[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "703600a239f419a1a002dacbd3b0b3312c5e840b"
os = "macos"

    [[aws_c_sdkutils.download]]
    sha256 = "b88e069cd98f1adb7cc8d4260e3da345bde5006f116e84cd54441363ae86ad7c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.aarch64-apple-darwin.tar.gz"
[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "fcb0f392a3343d90f781123e08ac334a07d0951f"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "0bae979360f049ecbfb7ed12a302eb229219f2c789e819d720675ff76135280d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.aarch64-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "aarch64"
git-tree-sha1 = "5f15fe9b78b34d4a504a92270cddf1dba3005789"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "9110cf4b26d78ab7adbb6a18c62434b330e23dd522dc0028557af75be7c1c02f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.aarch64-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7f1a910d9da8215c694a2b41287f1ab954da1b73"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "f27a1704a65f286437023b64aff2bba970928f7d84997e92cd794feb1002e5c7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "57e3a1ff9ad9fe33dbaea59d0b6d1c715afd23aa"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "73bc1ad19ec486cdc1b12413fa57068c453205cf8eb85bb6888b9a790edd84ae"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.armv6l-linux-musleabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11d743ee4332707997fba882b76ba23ae5f29a1d"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "b22ca87f7fc7c5284ba5bdab708cc9b92c855a8b099460d51acd41eb323cdde0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec386a3a80f52d6ed2cfc6c11ca396429005c619"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "a81c9b7a483645add830c789b4c8693ce8c24923033dd42fad99bf9b407bc535"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.armv7l-linux-musleabihf.tar.gz"
[[aws_c_sdkutils]]
arch = "i686"
git-tree-sha1 = "eeb7f604457ab1758b596cf6ebfa25d7822bd997"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "ab25e13b48587f7d24878da140cdc7b0254ff076596fd55186c140cc18546154"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.i686-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "i686"
git-tree-sha1 = "f9bfbc2d0bbed1951e5997ada953f80cc53846e8"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "8587cd37e4e8eddd103e364d7a621a0c15d9e707bbdb1913075bb919999072f2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.i686-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "powerpc64le"
git-tree-sha1 = "188023ab9ebafb6d3e96d655631019cab483198d"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "b254654292924eedccf16f6877234abd4c0435c5827af11c9088d59ce51ddb2a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.powerpc64le-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "5d8b9480d24a3f90ed8fd321b4f03eac9af0a53a"
os = "macos"

    [[aws_c_sdkutils.download]]
    sha256 = "07abdd4611f3825f991d2f3d7c0fb64f075219bd7a8a9e8ff9493ef8e9e23af7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.x86_64-apple-darwin.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "fcad7ec8a4712f235458cda92689ede349f53946"
libc = "glibc"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "49fd112c49416abb7032cc2756fe36e4ab6d8fe7b144f09a0d6825fe1e7a17fa"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.x86_64-linux-gnu.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "9a7bddc77face42207a8d2ec984e02c7516c6bcf"
libc = "musl"
os = "linux"

    [[aws_c_sdkutils.download]]
    sha256 = "40284c846b1ca2d1658519dca6149392ca2f78673dcb543baa2cbcf96609c59f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.x86_64-linux-musl.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "c4e75af56b349d86ae06c83689135843c364889f"
os = "freebsd"

    [[aws_c_sdkutils.download]]
    sha256 = "6b9b44785a83a143b4f29d202ba7204dea5cf16544b6edc330dfd39b1c31d8ff"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.x86_64-unknown-freebsd.tar.gz"
[[aws_c_sdkutils]]
arch = "x86_64"
git-tree-sha1 = "83c0d2f9150b4ded564cc304393508f31e5f876c"
os = "windows"

    [[aws_c_sdkutils.download]]
    sha256 = "6a5f145106dacf80bcb4da718889161b4cdbbc9fe8969868d3c8be199181897f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_sdkutils_jll.jl/releases/download/aws_c_sdkutils-v0.1.17+0/aws_c_sdkutils.v0.1.17.x86_64-w64-mingw32.tar.gz"
