# Autogenerated wrapper script for aws_c_sdkutils_jll for x86_64-unknown-freebsd
export libaws_c_sdkutils

using aws_c_common_jll
JLLWrappers.@generate_wrapper_header("aws_c_sdkutils")
JLLWrappers.@declare_library_product(libaws_c_sdkutils, "libaws-c-sdkutils.so.1.0.0")
function __init__()
    JLLWrappers.@generate_init_header(aws_c_common_jll)
    JLLWrappers.@init_library_product(
        libaws_c_sdkutils,
        "lib/libaws-c-sdkutils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
